[package]
name = "AoC2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = "0.4.1"
num = "0.4.1"
priority-queue = "1.3.2"
regex = "1.10.2"
